---
log_shipper_loki_url: ""
log_shipper_site_label: homelab
log_shipper_host_label: ""
log_shipper_docker: false
log_shipper_journal_units: []
log_shipper_heartbeat_unit: alloy-heartbeat.service
log_shipper_heartbeat_interval: 5min

log_shipper_user: alloy
log_shipper_group: alloy
log_shipper_config_dir: /etc/alloy
log_shipper_state_dir: /var/lib/alloy
log_shipper_cache_dir: /var/cache/log-shipper
log_shipper_extract_dir: /opt/log-shipper
log_shipper_bin_dir: /usr/local/bin
log_shipper_listen_address: 127.0.0.1:12345

log_shipper_version: "1.19.2"
log_shipper_project: grafana/alloy
log_shipper_tag: v1.19.2
log_shipper_archive: alloy-linux-amd64.zip
log_shipper_archive_sha256: 3694ea4e1044b367e1c21ffe28117f209c5989fa5e604d000321809f871ab701
