---
argument_specs:
  main:
    short_description: Deploy a pinned Home Assistant Container Compose project
    options:
      homeassistant_install_dir:
        type: str
      homeassistant_owner:
        type: str
      homeassistant_group:
        type: str
      homeassistant_image:
        type: str
      homeassistant_name:
        type: str
      homeassistant_tz:
        type: str
      homeassistant_external_url:
        type: str
      homeassistant_internal_url:
        type: str
      homeassistant_trusted_proxies:
        type: list
        elements: str
        required: true
      homeassistant_mqtt_broker:
        type: str
      homeassistant_mqtt_port:
        type: int
      homeassistant_mqtt_user:
        type: str
      homeassistant_mqtt_password:
        type: str
        required: true
